name: Fund Scraper Workflow

on:
  # 当以下文件被推送到仓库时，触发工作流
  push:
    paths:
      - 'scrape_all_funds.py'
      - '.github/workflows/scrape_funds.yml'
  # 允许手动在 GitHub Actions 界面触发工作流
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      # 设置环境变量，确保时间和日期使用中国上海时区
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      # 使用指定版本的 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      # 安装脚本所需的 Python 库
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz

    - name: Run script and push results
     
      run: python scrape_all_funds.py
