name: Fund Scraper Workflow

on:
  push:
    paths:
      - 'script.py'  # 当脚本变动时运行
      - '.github/workflows/fund-scraper.yml'  # 当YML变动时运行
  workflow_dispatch:  # 支持手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'  # 设置上海时区

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz

    - name: Run script
      run: python scrape_all_funds.py

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update basic info files from workflow" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
