# .github/workflows/strategy_runner.yml
name: 基金策略自动运行

on:
  # 1. 手动运行
  workflow_dispatch:
  
  # 2. 脚本或 YAML 变动时自动运行
  push:
    branches:
      - main
    paths:
      - 'strategy_script.py' # 脚本名称
      - '.github/workflows/strategy_runner.yml'

jobs:
  run_strategy:
    runs-on: ubuntu-latest
    
    env:
      TZ: Asia/Shanghai # 设置时区为上海时区

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: 安装依赖
      run: |
        # 新增 requests 库用于网络爬取 PB 数据
        pip install pandas numpy pytz requests
        
    - name: 运行策略脚本
      id: run_script
      run: |
        echo "检查 fund_data 目录..."
        
        if [ ! -d "fund_data" ]; then
          echo "::error::fund_data 目录不存在，请检查仓库结构！"
          exit 1
        fi
        
        # 运行策略
        python strategy_script.py

    - name: 提交新生成的推荐结果
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "自动策略运行: 添加新的基金推荐结果 (PB+跌幅Top1)"
        file_pattern: "推荐结果/**/*.csv" 
        skip_ci: true 
        commit_user_name: 'GitHub Actions Bot'
        commit_user_email: 'actions@github.com'
