# .github/workflows/strategy_runner.yml
name: 基金资料抓取

on:
  # 1. 手动运行
  workflow_dispatch:
  
  # 2. 脚本或 YAML 变动时自动运行
  push:
    branches:
      - main
    paths:
      - 'strategy_script.py' 
      - '.github/workflows/strategy_runner.yml'

jobs:
  run_strategy:
    runs-on: ubuntu-latest
    
    env:
      TZ: Asia/Shanghai # 设置时区为上海时区

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: 安装依赖
      run: |
        # 安装 pandas, numpy, pytz, requests, beautifulsoup4 库
        pip install pandas numpy pytz requests beautifulsoup4
        
    - name: 运行资料抓取脚本
      id: run_script
      run: |
        echo "检查 fund_data 目录..."
        
        if [ ! -d "fund_data" ]; then
          echo "::error::fund_data 目录不存在，请检查仓库结构！"
          exit 1
        fi
        
        # 运行脚本
        python strategy_script.py

    - name: 提交新抓取的资料数据
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # 更新 commit message
        commit_message: "自动资料抓取: 添加最新的基金 PB 数据"
        # 更新文件匹配模式，匹配新的输出目录 'fetched_pb_data'
        file_pattern: "fetched_pb_data/**/*.csv" 
        skip_ci: true 
        commit_user_name: 'GitHub Actions Bot'
        commit_user_email: 'actions@github.com'
